// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkCqimLtb1TB9OGTNlRAmVHNolGv6ncE',
    appId: '1:264457314789:web:4079fb9318f3eef02c0f0c',
    messagingSenderId: '264457314789',
    projectId: 'prato-do-dia-15876',
    authDomain: 'prato-do-dia-15876.firebaseapp.com',
    storageBucket: 'prato-do-dia-15876.firebasestorage.app',
    measurementId: 'G-0R86V1TLCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoDZN8lYnQ3c_44FiR0QrcfRewhVV5utI',
    appId: '1:264457314789:android:cef78c8378ae06b92c0f0c',
    messagingSenderId: '264457314789',
    projectId: 'prato-do-dia-15876',
    storageBucket: 'prato-do-dia-15876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztGn0Rlx9PiZUBMzPZuU1FMEDDnnA4a0',
    appId: '1:264457314789:ios:d89f4b29c88fe5452c0f0c',
    messagingSenderId: '264457314789',
    projectId: 'prato-do-dia-15876',
    storageBucket: 'prato-do-dia-15876.firebasestorage.app',
    iosBundleId: 'com.example.appTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztGn0Rlx9PiZUBMzPZuU1FMEDDnnA4a0',
    appId: '1:264457314789:ios:d89f4b29c88fe5452c0f0c',
    messagingSenderId: '264457314789',
    projectId: 'prato-do-dia-15876',
    storageBucket: 'prato-do-dia-15876.firebasestorage.app',
    iosBundleId: 'com.example.appTeste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdkCqimLtb1TB9OGTNlRAmVHNolGv6ncE',
    appId: '1:264457314789:web:2170b034325557562c0f0c',
    messagingSenderId: '264457314789',
    projectId: 'prato-do-dia-15876',
    authDomain: 'prato-do-dia-15876.firebaseapp.com',
    storageBucket: 'prato-do-dia-15876.firebasestorage.app',
    measurementId: 'G-BYGN3RG7Z0',
  );

}